[workspace]
members = [".", "agility-macros"]

[package]
name = "agility"
version = "0.1.0"
edition = "2024"

[dependencies]
agility-macros = { path = "agility-macros" }
orx-concurrent-vec = "3.10.0"

[dev-dependencies]
trybuild = "1.0"
